CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_MUSICA_2ANOA;
USE BD_APLICATIVO_MUSICA_2ANOA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR (14) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL, 
    IDADE INTEGER  NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    RITMO VARCHAR (50) NOT NULL,
	PUBLICO_ALVO VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    FOTO BLOB,
    FK_CPF_ARTISTA VARCHAR (14) NOT NULL,
    FOREIGN KEY (FK_CPF_ARTISTA) REFERENCES ARTISTA (CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    MUSICA VARCHAR (255) NOT NULL,
    NOME VARCHAR (255) NOT NULL,
    FK_ID_ALBUM INTEGER,
    FK_ID_GENERO INTEGER,
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM (ID),
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO (ID)
);