CREATE DATABASE IF NOT EXISTS BD_CONSULTAS_MEDICAS_2ANO;
USE BD_CONSULTAS_MEDICAS_2ANO;

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR (20) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    ESPECIALIDADE VARCHAR (255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR (20) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR (15) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    AGENDAMENTO VARCHAR (255) NOT NULL,
    TIPO VARCHAR (255) NOT NULL,
	FK_CRM_MEDICO INTEGER,
    FK_CPF_PACIENTE VARCHAR (14),
    FOREIGN KEY (FK_CRM_MEDICO) REFERENCES MEDICO(CRM)ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_PACIENTE) REFERENCES PACIENTE(CPF)ON DELETE CASCADE
);