CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO  DATE NOT NULL,
    USU_LOGIN VARCHAR (255) NOT NULL UNIQUE,
	USU_AREA_ATUACAO VARCHAR (500), 
    USU_PROFISSAO VARCHAR (200),
    USU_AREA_FORMACAO VARCHAR (500),
    USU_DATANASC  DATE NOT NULL, 
    USU_ESTADO_CIVIL ENUM("SOLTEIRO","CASADO","DIVORCIADO","VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR (2) NOT NULL, 
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL","MEDIO", "SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR (255) NOT NULL,
    PRIMARY KEY (USU_CODIGO)
);	

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_FINAL DATE,
    END_DATA_FINAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(500) NOT NULL,
    ENQ_NOME VARCHAR (255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
	PRIMARY KEY(ENQ_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE
);	

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	USE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY(USE_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);	

CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR (500) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY(PER_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);	

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR (500) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER NOT NULL,
    PRIMARY KEY(RES_CODIGO),
    FOREIGN KEY(FK_PER_CODIGO) REFERENCES PERGUNTAS (PER_CODIGO) ON DELETE CASCADE
);	

SELECT * FROM USUARIO;

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES ("2025-10-01","littlenocolis","direito","2009-04-29", "SOLTEIRO", "SP", "MEDIO", "nicolygeribola@gmail.com","nicoly123","Nicoly");

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES ("2025-10-01","july","Relações Internacionais","2009-03-04", "SOLTEIRO", "SP", "MEDIO", "juliasavella@gmail.com","julia123","Julia");

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES ("2025-10-01","laurabaldy","EEAR","2008-10-06", "CASADO", "SP", "MEDIO", "laurabaldy@gmail.com","laura123","Laura");

SELECT * FROM ENQUETE;
INSERT INTO ENQUETE (END_DATA_FINAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES ("2025-10-01","abobrinhaslaoqslaoq","Formulario1","1");

INSERT INTO ENQUETE (END_DATA_FINAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES ("2025-11-01","beterrabaslaoq","Formulario2","1");

INSERT INTO ENQUETE (END_DATA_FINAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES ("2025-12-01","mamaoslaoq","Formulario3","3");

SELECT * FROM  USUARIO_RESPONDE_ENQUETE;

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA,FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-10-01", "1", "1");

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA,FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES  ("2025-11-01", "1", "1");

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA,FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-12-01", "3", "3");

SELECT * FROM  PERGUNTAS;

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES("slaoq","1");

INSERT INTO PERGUNTAS( PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES("babosaoq","1");

INSERT INTO PERGUNTAS( PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES("valameudeus","1");

SELECT * FROM  RESPOSTAS;

INSERT INTO RESPOSTAS(RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("asjdkakd","a", "1");


INSERT INTO RESPOSTAS(RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("asdkaskdka","b", "2");


INSERT INTO RESPOSTAS(RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("dasdasdj","c", "3");

SELECT * FROM PERGUNTAS;
SELECT * FROM RESPOSTAS;
SELECT * FROM USUARIO;
SELECT * FROM ENQUETE;
SELECT * FROM USUARIO_RESPONDE_ENQUETE;