CREATE DATABASE IF NOT EXISTS BD_GEESTAO_CURSOS_2ANO;
USE BD_GEESTAO_CURSOS_2ANO;

CREATE TABLE IF NOT EXISTS PROFESSOR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    TITULACAO VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUNO(
	RM INTEGER PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS CURSO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    DESCRICAO VARCHAR (255) NOT NULL,
    CARGA_HORARIA VARCHAR (255) NOT NULL,
    FK_ID_PROFESSOR INTEGER,
    FOREIGN KEY (FK_ID_PROFESSOR) REFERENCES PROFESSOR (ID)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS POSSUI(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_CURSO INTEGER,
    FK_RM_ALUNO INTEGER,
    FOREIGN KEY (FK_ID_CURSO) REFERENCES CURSO (ID)ON DELETE CASCADE,
    FOREIGN KEY (FK_RM_ALUNO) REFERENCES ALUNO (RM)ON DELETE CASCADE
);