CREATE DATABASE IF NOT EXISTS BD_GERENCIADOR_PROJETOS_2ANO;
USE BD_GERENCIADOR_PROJETOS_2ANO;

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT  PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    DATA DATE
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR (14) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    AREA VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRAZO DATE,
    TIPO VARCHAR (255) NOT NULL,
    FK_ID_PROJETO INTEGER,
    FK_CPF_FUNCIONRIO VARCHAR (14),
    FOREIGN KEY (FK_ID_PROJETO) REFERENCES PROJETO (ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_FUNCIONRIO) REFERENCES FUNCIONARIO (CPF) ON DELETE CASCADE
);

