CREATE DATABASE IF NOT EXISTS BD_GEREN_BIBLIO_DIG_2ANO;
USE BD_GEREN_BIBLIO_DIG_2ANO;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR (14) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    GENERO VARCHAR (255) NOT NULL,
    CONTATO VARCHAR (15) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    DESCRICAO VARCHAR (255) NOT NULL,
    GENERO VARCHAR (15) NOT NULL
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR (14) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR (15) NOT NULL
);

CREATE TABLE IF NOT EXISTS ACESSAR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	FK_ID_LIVRO_DIGITAL INTEGER,
    FK_CPF_LEITOR VARCHAR (14),
    FOREIGN KEY (FK_ID_LIVRO_DIGITAL) REFERENCES LIVRO_DIGITAL(ID),
    FOREIGN KEY (FK_CPF_LEITOR) REFERENCES LEITOR(CPF)
);