CREATE DATABASE IF NOT EXISTS BD_GESTAO_ESTOQUE_2ANO;
USE BD_GESTAO_ESTOQUE_2ANO;

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    VALIDADE DATE
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR (14) PRIMARY KEY,
    TELEFONE VARCHAR (15) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR (255),
    NOME VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_PRODUTO INTEGER,
    FK_CNPJ_FORNECEDOR VARCHAR (14),
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO (ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CNPJ_FORNECEDOR ) REFERENCES FORNECEDOR (CNPJ) ON DELETE CASCADE
);
