CREATE DATABASE IF NOT EXISTS BD_RESEVAS_AEREAS_2ANO;
USE BD_RESEVAS_AEREAS_2ANO;

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR (14) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    IDADE INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    COMIDA VARCHAR (255) NOT NULL,
    LOCAL VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CONFORTO VARCHAR (255) NOT NULL,
    CLASSE VARCHAR (255) NOT NULL,
    FK_CPF_PASSAGEIRO VARCHAR (14),
    FK_ID_VOO INTEGER,
    FOREIGN KEY (FK_CPF_PASSAGEIRO) REFERENCES PASSAGEIRO(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_VOO) REFERENCES VOO(ID) ON DELETE CASCADE
);
