CREATE DATABASE IF NOT EXISTS BD_STREAMING_VIDEO_2ANO;
USE BD_STREAMING_VIDEO_2ANO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    IDADE INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    FK_ID_CATEGORIA INTEGER,
    FOREIGN KEY (FK_ID_CATEGORIA ) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS VISUALIZACAO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    INTERACAO VARCHAR (255) NOT NULL,
    FK_ID_VIDEO INTEGER,
    FOREIGN KEY (FK_ID_VIDEO ) REFERENCES VIDEO(ID) ON DELETE CASCADE 
);

